export { createArray } from './createArray'
export { errorLog } from './errorLog'
export { isFunc } from './isFunc'
export { isObject } from './isObject'
export { isString } from './isString'
export { roundOff } from './roundOff'
export { scrollAnimationInit } from './scrollAnimationInit'
export { stringContains } from './stringContains'
